### ISSUE TITLE
leak password try `bfg` to remove

### ISSUE THREAD

**Issue by ninyawee** [vnurhaqiqi/fastapi-sqlmodel-postgresql#2]
https://github.com/vnurhaqiqi/fastapi-sqlmodel-postgresql/blob/4f1ac152345ff031b0ed284bf3676a93196e1534/alembic.ini#L53

**Comment by vnurhaqiqi** [comment]
Thank's, ill fix it 🙏

**Comment by vnurhaqiqi** [comment]
Fixed [here](https://github.com/vnurhaqiqi/fastapi-sqlmodel-postgresql/pull/3)

**Comment by ninyawee** [comment]
umm it is still in git history, just not latest commit

**Comment by ninyawee** [comment]
you have to force push all dirty commit
ref to <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository>

```bash 
$ bfg --replace-text pass.txt
# and follow the prompt
```
